### PR TITLE
Add support for tagging EBS volumes

### PR DESCRIPTION
**Pull request by cristim**

### CODE REVIEW

**Comment by mpostument** [comment]
Looks good

**Comment by mpostument** [comment]
https://github.com/mpostument/awstaghelper/releases/tag/0.19.0

**Comment by cristim** [comment]
Awesome, thanks!

BTW, hope you don't mind I've used ChatGPT for this, I basically gave it the EC2 instances tagging code and asked it to convert it to EBS volumes, and did this file by file.

It converted the calls to EBS and worked like a charm with just a couple of manual fixes because some of the functions were named differently and had to be renamed to match.

**Comment by mpostument** [comment]
No problem with ChatGPT at all :)

**Pull request merged**
